apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: karydiasecuritypolicies.karydia.gardener.cloud
spec:
  group: karydia.gardener.cloud
  version: v1alpha1
  scope: Cluster
  names:
    kind: KarydiaSecurityPolicy
    plural: karydiasecuritypolicies
    shortNames:
      - ksp
