apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: karydiasecuritypolicies.karydia.gardener.cloud
spec:
  group: karydia.gardener.cloud
  version: v1alpha1
  scope: Cluster
  names:
    kind: KarydiaSecurityPolicy
    plural: karydiasecuritypolicies
    shortNames:
      - ksp
  validation:
    # Documentation for all possible settings can be found here:
    # https://github.com/kinvolk/karydia#karydiasecuritypolicy
    openAPIV3Schema:
      properties:
        spec:
          properties:
            pod:
              properties:
                automountServiceAccountToken:
                  type: string
                seccompProfile:
                  type: string
