---

apiVersion: karydia.gardener.cloud/v1alpha1
kind: KarydiaSecurityPolicy
metadata:
  name: default
spec:
  pod:
    automountServiceAccountToken: "non-default"

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ksp-default
rules:
- apiGroups: ['karydia.gardener.cloud']
  resources: ['karydiasecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ksp
roleRef:
  kind: ClusterRole
  name: ksp-default
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: endpoint-controller
  namespace: kube-system
- kind: ServiceAccount
  name: deployment-controller
  namespace: kube-system
- kind: ServiceAccount
  name: replicaset-controller
  namespace: kube-system
- kind: User
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: generic-garbage-collector
  namespace: kube-system
- kind: User
  name: system:kube-controller-manager
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:apiserver
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: kube-apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
