apiVersion: v1
kind: ServiceAccount
metadata:
  name: karydia
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia
  namespace: kube-system
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: karydia
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
